### ISSUE TITLE
 登录失败

### ISSUE THREAD

**Issue by Steve662024** [XJouYi/SinaWeibo#4]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\spider\src\project\weibo\index.py", line 36, in <module>
    wb = Weibo("********", "**********")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\SinaWeibo\weibo.py", line 33, in __init__
    self.__login()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\SinaWeibo\weibo.py", line 55, in __login
    raise e
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\SinaWeibo\weibo.py", line 50, in __login
    login_info = json.loads(re.search('\((\{.*\})\)', resp.text).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by XJouYi** [comment]
试过是成功的，这个错误可能是密码不对，或者就是图形验证码的问题。新浪微博针对账户登录会做IP校验，如果发现登录IP变动较大的话会要求用户输入图形验证码。我找个时间加上这个功能

**Comment by Steve662024** [comment]
那应该是图像验证码的问题了，我本地电脑可以登录，服务器上登录失败。

**Comment by XJouYi** [comment]
还有一种可能是IP屏蔽，如果是通过阿里云服务器的话，新浪是做了屏蔽的，估计国内各大云平台都被屏蔽了

**Comment by Steve662024** [comment]
没有屏蔽，我试了下可以访问https://weibo.com/login.php
