### ISSUE TITLE
centos+python3.6 发生报错

### ISSUE THREAD

**Issue by wefinger** [XJouYi/SinaWeibo#6]
错误信息：
Traceback (most recent call last):                                                        
  File "<stdin>", line 1, in <module>                                                     
  File "/usr/local/lib/python3.6/dist-packages/SinaWeibo/weibo.py", line 33, in __init__  
    self.__login()                                                                        
  File "/usr/local/lib/python3.6/dist-packages/SinaWeibo/weibo.py", line 55, in __login   
    raise e                                                                               
  File "/usr/local/lib/python3.6/dist-packages/SinaWeibo/weibo.py", line 50, in __login   
    login_info = json.loads(re.search('\((\{.*\})\)', resp.text).group(1))                
AttributeError: 'NoneType' object has no attribute 'group'                

产生错误的时候我觉得是正则的问题。。然后改了改正则，发现好像没用         
本机windows+python3.6使用正常。

**Comment by MarvellousBaby** [comment]
会不会是linux和win的/不同的问题
